### ISSUE TITLE
Please add me as a contributor to this repo

### ISSUE THREAD

**Issue by ravigadhia** [GitHub-Users-Groups/SoCal-GUG#5]
Hi, 

If you'd like to be added as a contributor to this Repo, please add your name & specify the type of access you'd like (Admin or Write).

Thank you!

**Comment by nfultz** [comment]
@nfultz - write

**Comment by ctrlaltdev** [comment]
- [ ] @ctrlaltdev - write

**Comment by ravigadhia** [comment]
Closing to clean up my inbox.
